# These are supported funding model platforms

# Inserisci il tuo nome utente se fai parte del programma ufficiale GitHub Sponsors
github: [emarucci1977-hub]

# Se usi PayPal o un sito personale, inserisci l'URL completo (massimo 4 link)
custom: ['[Offrimi un caffè su PayPal](https://paypal.me/EliseoMarucci')
']

